process.env.DATABASE_URL =
  'postgresql://turborepo:turborepo@localhost:5432/turborepo_test?schema=public';
process.env.DIRECT_URL =
  'postgresql://turborepo:turborepo@localhost:5432/turborepo_test?schema=public';
process.env.JWT_SECRET = 'test-jwt-secret-key-for-testing-only-min-32-chars';
process.env.JWT_EXPIRES_IN_ACCESS = '15m';
process.env.JWT_EXPIRES_IN_REFRESH = '7d';
process.env.JWT_ISSUER = 'turborepo-api';
process.env.JWT_AUDIENCE = 'turborepo-client';
process.env.COOKIE_SECURE = 'false';
process.env.CORS_ORIGINS = 'http://localhost:3000';
process.env.THROTTLE_TTL = '1';
process.env.THROTTLE_LIMIT = '100000';
